spring.application.name=myfirstspringbootproj
#Mysql connection configuration
spring.datasource.url=jdbc:mysql://localhost:3306/firstSpringBootProjDB?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=test1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
